### ISSUE TITLE
Use uglified js file

### ISSUE THREAD

**Issue by maxgrossman** [MissingMaps/microsites#22]
Upon upgrading the dependencies, the uglified javascript file that controls country pages is not being generated. Currently, the non-uglified version is being used, which works fine. However, this should be fixed in the future.

**Comment by dalekunce** [comment]
this is an issue for the main site as well. :(

**Comment by maxgrossman** [comment]
final fix here -> b2c0a3e1d3f5bd7caf57892515212dbcfe8f34c6

I did the following. 

1) use [gulp-bundle-assets](https://www.npmjs.com/package/gulp-bundle-assets) in a gulp task. Instead of piping the uglification in the staging/production build, this plugin reads from a config file in which you specify in which env (dev, stage, prod) to uglify. 
2) after generating the files (which have a nomenclature specific to the gulp plugin), rename them to a .min.js.

**Comment by dalekunce** [comment]
@maxgrossman would you mind stubbing this out for the main site?
